os:
  - linux

language: java
sudo: true
git:
  submodules: false

## ----------------------------------------------------------------------
## Build tools
## ----------------------------------------------------------------------


## ----------------------------------------------------------------------
## Perform build:
## ----------------------------------------------------------------------

script:

  - mvn clean install -DskipTests


## ----------------------------------------------------------------------
## Notification
## ----------------------------------------------------------------------
notifications:
  email:
    recipients:
      - jiayu2@asu.edu
    on_success: always
    on_failure: always
