os:
  - linux
dist: xenial
language: scala
jdk:
  - openjdk8
python:
  - "3.7"
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U wheel
  - sudo pip3 install -U virtualenvwrapper
install:
- python3 -m pip install pipenv
- wget https://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
- tar -xzf spark-2.4.4-bin-hadoop2.7.tgz
- rm spark-2.4.4-bin-hadoop2.7.tgz

script:
  - (cd python;pipenv install --dev) 
  - export SPARK_HOME=$PWD/spark-2.4.4-bin-hadoop2.7
  - export PYTHONPATH=$SPARK_HOME/python
  - mvn -q clean install
  - find core/target/ -iregex "core\/target\/geospark-[0-9]\.[0-9]\.[0-9]\.jar" -exec cp {} $SPARK_HOME/jars \;
  - find sql/target/ -iregex "sql\/target\/geospark-sql_[0-9]\.[0-9]-[0-9]\.[0-9]\.[0-9]\.jar" -exec cp {} $SPARK_HOME/jars \;
  - (cd python;pipenv run pytest tests)
